#!/usr/bin/env python3
"""
Derive a wayfinder map's frontier from the filesystem, and check the map for drift.

Truth is a ticket file's location plus its fields, so nothing reported here is
stored anywhere — except map.md's two index sections, which are generated blocks
this script rebuilds with --sync-map.

Usage:
  frontier.py <effort-slug|effort-dir>                 # read-only report
  frontier.py <effort-slug|effort-dir> --sync-map      # rebuild map.md's indexes
  frontier.py <effort-slug|effort-dir> --resolve NAME  # file an answered ticket
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

GEN_START = "<!-- generated by frontier.py --sync-map; do not hand-edit -->"
GEN_END = "<!-- /generated -->"
DECISIONS = "## Decisions so far"
OUT_OF_SCOPE = "## Out of scope"
ANSWER = "## Answer"


def field(content: str, name: str) -> str:
    """First `Name: value` line, case-insensitively. '' if absent, empty, or 'none'."""
    prefix = f"{name.lower()}:"
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith(prefix):
            value = stripped.split(":", 1)[1].strip()
            return "" if value.lower() == "none" else value
    return ""


def has_heading(content: str, heading: str) -> bool:
    """Whether `heading` appears as a heading line of its own."""
    return any(line.strip().lower() == heading.lower() for line in content.splitlines())


def recording_kind(content: str) -> Optional[str]:
    """'answered' or 'out of scope' if the ticket has recorded which; else None."""
    if has_heading(content, ANSWER):
        return "answered"
    if has_heading(content, OUT_OF_SCOPE):
        return "out of scope"
    return None


def filename_stem(name: str) -> str:
    """Filename without `.md`. The identity of a ticket still in tickets/."""
    return name[:-3] if name.endswith(".md") else name


def split_seq(name: str) -> Tuple[Optional[int], str]:
    """`03-push-or-email.md` -> (3, 'push-or-email'). Unnumbered -> (None, stem).

    Only resolved/ files carry an `NN-` prefix. Do not use this to parse a name
    in tickets/ or a `Blocked by:` value — `2024-review` is an identity, not seq 2024.
    """
    base = filename_stem(name)
    m = re.match(r"^(\d+)-(.+)$", base)
    return (int(m.group(1)), m.group(2)) if m else (None, base)


def deps_of(content: str) -> List[str]:
    """Ticket names in `Blocked by:`, as written (no `.md`), not stripped of digits."""
    names = [d.strip() for d in field(content, "Blocked by").split(",") if d.strip()]
    return [filename_stem(n) for n in names]


class Report:
    """What one scan of an effort directory found."""

    def __init__(self) -> None:
        self.frontier: List[str] = []
        self.claimed: List[str] = []
        self.blocked: List[str] = []
        self.dangling: List[str] = []
        # Integrity problems, not states.
        self.needs_filing: List[str] = []
        self.unrecorded: List[str] = []
        self.unnumbered: List[str] = []
        self.duplicate_seq: List[str] = []
        # resolved/ contents, for the map indexes. Keyed by filename.
        self.decisions: Dict[str, str] = {}
        self.out_of_scope: Dict[str, str] = {}
        self.drift: List[str] = []
        # Bare stems present in resolved/, so `Blocked by:` survives renaming.
        self.resolved_stems: Dict[str, str] = {}

    def integrity(self) -> List[Tuple[str, List[str]]]:
        return [
            ("NEEDS FILING", self.needs_filing),
            ("UNRECORDED", self.unrecorded),
            ("UNNUMBERED", self.unnumbered),
            ("DUPLICATE NUMBERS", self.duplicate_seq),
            ("DANGLING BLOCKERS", self.dangling),
            ("MAP OUT OF SYNC", self.drift),
        ]


def scan(effort: Path) -> Report:
    """Classify every ticket. Reads only; never writes."""
    tickets, resolved = effort / "tickets", effort / "resolved"
    if not tickets.is_dir():
        sys.exit(f"not a wayfinder effort: {effort} (no tickets/ directory)")

    r = Report()

    seen_seq: Dict[int, str] = {}
    for path in sorted(resolved.glob("*.md")) if resolved.is_dir() else []:
        content = path.read_text(encoding="utf-8")
        gist = field(content, "Gist") or "(no gist recorded)"
        seq, stem = split_seq(path.name)
        r.resolved_stems[stem] = path.name

        if seq is None:
            r.unnumbered.append(path.name)
        elif seq in seen_seq:
            r.duplicate_seq.append(f"{seq:02d}: {seen_seq[seq]} and {path.name}")
        else:
            seen_seq[seq] = path.name

        kind = recording_kind(content)
        if kind == "answered":
            r.decisions[path.name] = gist
        elif kind == "out of scope":
            r.out_of_scope[path.name] = gist
        else:
            # Moved off the frontier without recording an answer or a reason.
            r.unrecorded.append(path.name)

    open_stems = {filename_stem(p.name): p.name for p in tickets.glob("*.md")}

    for path in sorted(tickets.glob("*.md")):
        name, content = path.name, path.read_text(encoding="utf-8")

        open_deps, bad = [], False
        for dep in deps_of(content):
            if dep in open_stems:
                open_deps.append(open_stems[dep])
            elif dep not in r.resolved_stems:
                r.dangling.append(f"{name} -> {dep}")
                bad = True

        claim = field(content, "Claimed")

        # Order matters: a recorded ticket is a filing problem whatever else
        # is true of it, and an unresolvable blocker means "blocked?" is unknown.
        kind = recording_kind(content)
        if kind:
            r.needs_filing.append(f"{name} ({kind}, still in tickets/)")
        elif bad:
            pass  # listed under DANGLING only — never takeable
        elif open_deps:
            r.blocked.append(f"{name} <- {', '.join(open_deps)}")
        elif claim:
            r.claimed.append(f"{name} (claimed: {claim})")
        else:
            r.frontier.append(name)

    return r


def entry(name: str, gist: str) -> str:
    """One index line: a link wrapping the ticket's name, plus its gist."""
    seq, stem = split_seq(name)
    label = f"{seq:02d}. {stem}" if seq is not None else stem
    return f"- [{label}](resolved/{name}) — {gist}"


def block_span(lines: List[str], heading: str) -> Optional[Tuple[int, int]]:
    """(start, end) of the generated block under `heading`, or None if absent."""
    try:
        head = next(i for i, l in enumerate(lines) if l.strip().lower() == heading.lower())
    except StopIteration:
        return None
    start = None
    for i in range(head + 1, len(lines)):
        if lines[i].startswith("## "):
            break
        if lines[i].strip() == GEN_START:
            start = i
        elif lines[i].strip() == GEN_END and start is not None:
            return start, i
    return None


def indexed_names(lines: List[str], span: Optional[Tuple[int, int]]) -> List[str]:
    """Ticket filenames already listed inside a generated block."""
    if span is None:
        return []
    names = []
    for line in lines[span[0] + 1 : span[1]]:
        if "](resolved/" in line:
            names.append(line.split("](resolved/", 1)[1].split(")", 1)[0])
    return names


def in_route_order(names: List[str]) -> List[str]:
    """Sort by the `NN-` prefix: resolution order, derived from the filename.

    The order is not stored anywhere, so it cannot go stale. Unnumbered files
    sort last — they are reported separately as a problem to fix.
    """
    return sorted(names, key=lambda n: (split_seq(n)[0] is None, split_seq(n)[0] or 0, n))


def check_drift(r: Report, map_path: Path) -> None:
    """Compare map.md's generated indexes against resolved/. Records, never fixes."""
    if not map_path.exists():
        r.drift.append("map.md is missing")
        return
    lines = map_path.read_text(encoding="utf-8").splitlines()
    for heading, expected in ((DECISIONS, r.decisions), (OUT_OF_SCOPE, r.out_of_scope)):
        label = heading.lstrip("# ")
        span = block_span(lines, heading)
        if span is None and expected:
            r.drift.append(f"{label}: no generated block, {len(expected)} to index")
            continue
        listed = set(indexed_names(lines, span))
        for missing in sorted(set(expected) - listed):
            r.drift.append(f"{label}: missing {missing}")
        for extra in sorted(listed - set(expected)):
            r.drift.append(f"{label}: lists {extra}, not in resolved/")


def sync_map(r: Report, map_path: Path) -> List[str]:
    """Rebuild map.md's two generated blocks. Idempotent; touches nothing else."""
    if not map_path.exists():
        sys.exit(f"cannot sync: {map_path} does not exist")

    lines = map_path.read_text(encoding="utf-8").splitlines()
    changed = []

    for heading, expected in ((DECISIONS, r.decisions), (OUT_OF_SCOPE, r.out_of_scope)):
        span = block_span(lines, heading)
        body = [entry(n, expected[n]) for n in in_route_order(list(expected))]
        new = [GEN_START, *body, GEN_END]

        if span is not None:
            if lines[span[0] : span[1] + 1] == new:
                continue
            lines[span[0] : span[1] + 1] = new
        elif not body:
            continue  # nothing to index yet — don't plant an empty block
        else:
            try:
                head = next(
                    i for i, l in enumerate(lines) if l.strip().lower() == heading.lower()
                )
            except StopIteration:
                sys.exit(f"cannot sync: map.md has no '{heading}' heading")
            lines[head + 1 : head + 1] = ["", *new]
        changed.append(f"{heading.lstrip('# ')}: {len(body)} entries")

    if changed:
        map_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return changed


def require_map(map_path: Path) -> None:
    """Fail before moving a ticket if the map cannot be synced afterwards."""
    if not map_path.exists():
        sys.exit(f"cannot resolve: {map_path} does not exist — write map.md first")
    headings = {line.strip().lower() for line in map_path.read_text(encoding="utf-8").splitlines()}
    for heading in (DECISIONS, OUT_OF_SCOPE):
        if heading.lower() not in headings:
            sys.exit(f"cannot resolve: map.md has no '{heading}' heading")


def move_file(src: Path, dst: Path) -> None:
    """Prefer `git mv` so history follows the ticket; fall back to rename if untracked."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        sys.exit(f"already exists: {dst}")
    proc = subprocess.run(
        ["git", "mv", "--", str(src), str(dst)],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        src.rename(dst)


def resolve(effort: Path, ticket: str) -> str:
    """File an answered ticket: allocate the next `NN-`, then move it to resolved/.

    One move, as before — the number rides along in the destination name.
    """
    tickets, resolved = effort / "tickets", effort / "resolved"
    src = tickets / (ticket if ticket.endswith(".md") else f"{ticket}.md")
    if not src.exists():
        want = filename_stem(ticket)
        matches = [p for p in tickets.glob("*.md") if filename_stem(p.name) == want]
        if len(matches) != 1:
            sys.exit(f"no such open ticket: {ticket}")
        src = matches[0]

    content = src.read_text(encoding="utf-8")
    if recording_kind(content) is None:
        sys.exit(
            f"{src.name} has neither '{ANSWER}' nor '{OUT_OF_SCOPE}' — "
            "record the resolution before filing it"
        )

    resolved.mkdir(exist_ok=True)
    used = [s for s, _ in (split_seq(p.name) for p in resolved.glob("*.md")) if s is not None]
    dst = resolved / f"{max(used, default=0) + 1:02d}-{filename_stem(src.name)}.md"
    move_file(src, dst)
    return f"{src.name} -> resolved/{dst.name}"


def section(label: str, items: List[str]) -> None:
    print(f"{label} ({len(items)})")
    print("\n".join(f"  {i}" for i in items) if items else "  —")


def print_hints(r: Report) -> None:
    hints: List[str] = []
    for item in r.needs_filing:
        name = filename_stem(item.split()[0])
        hints.append(f"file it: --resolve {name}")
    if r.unrecorded:
        hints.append("in resolved/ with no ## Answer and no ## Out of scope; record which")
    if r.unnumbered:
        hints.append("in resolved/ without an NN- prefix, so it has no place in the route")
    if r.duplicate_seq:
        hints.append("two tickets claim one position; renumber the later one")
    if r.dangling:
        hints.append("a blocker naming no file in tickets/ or resolved/; fix the name")
    if r.drift:
        missing = any(d == "map.md is missing" for d in r.drift)
        hints.append("write map.md first" if missing else "run with --sync-map")
    if hints:
        print()
        for hint in hints:
            print(f"  → {hint}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Derive a wayfinder map's frontier from the filesystem."
    )
    parser.add_argument("effort", help="effort slug, or path to the effort directory")
    parser.add_argument(
        "--sync-map",
        action="store_true",
        help="rebuild map.md's Decisions-so-far and Out-of-scope indexes",
    )
    parser.add_argument(
        "--resolve",
        metavar="TICKET",
        help="file an answered ticket: allocate the next NN-, move it, sync the map",
    )
    args = parser.parse_args()

    effort = Path(args.effort)
    if not effort.is_dir():
        effort = Path("docs/wayfinder") / args.effort
        if not effort.is_dir():
            print(f"no such effort: {args.effort}", file=sys.stderr)
            sys.exit(2)

    map_path = effort / "map.md"

if args.resolve:
        require_map(map_path)
        scan(effort)  # validates the effort layout before moving anything
        print(resolve(effort, args.resolve))
        changed = sync_map(scan(effort), map_path)
        print("map.md synced: " + ("; ".join(changed) if changed else "already current"))
        return

    r = scan(effort)

    if args.sync_map:
        changed = sync_map(r, map_path)
        print("map.md synced: " + ("; ".join(changed) if changed else "already current"))
        return

    check_drift(r, map_path)

    # Integrity first: a leftover resolution must be seen before FRONTIER, or
    # the next session takes a new ticket and the half-filed one stalls forever.
    printed = False
    for label, items in r.integrity():
        if not items:
            continue
        if printed:
            print()
        section(label, items)
        printed = True
    if printed:
        print_hints(r)
        print()
    section("FRONTIER", r.frontier)
    print()
    section("CLAIMED", r.claimed)
    print()
    section("BLOCKED", r.blocked)


if __name__ == "__main__":
    main()
